# dataset info
backbone: 'i3d'
dataset: "ActivityNet1.3"
data_path: "./dataset/ActivityNet1.3"
frames_per_sec: 25
segment_frames_num: 16
feature_dim: 2048  #2048
tIoU_thresh: "np.linspace(0.5, 0.95, 10)"
blocked_videos: ['video_test_0000270','video_test_0001292','video_test_0001496'] # We excluded three test videos (270, 1292, 1496) following LACP.

# training params
num_segments: -1 #-1
num_workers: 4
num_iters: 5000
test_iter: 500
batch_size: 64 # 16
lr: 0.0001
weight_decay: 0.001  # 0.0005
dropout: 0.7
r_act: 8
lambdas: "[0.5, 0.5, 1, 1]"
RAB_args: {'layer_num': 2, 'drop_out': 0.3, 'num_heads': 8, 'dim_feedforward': 128}

# stage2 params
max_epochs: 20
test_epoch: 1
batch_size2: 40
lr2: 0.00005
weight_loss_score: 1
weight_loss_reg: 1
max_proposal: 200


# post processing params
scale: 2
class_thresh: 0.5
#act_thresh_cas: "np.arange(0.0, 0.25, 0.025)"
#act_thresh_agnostic: "np.arange(0.5, 0.725, 0.025)"
act_thresh_cas: "np.arange(0.0, 0.3, 0.025)"
act_thresh_agnostic: "np.arange(0.5, 0.75, 0.025)"
#act_thresh_cas: "np.arange(0.0, 0.2, 0.025)"
#act_thresh_agnostic: "np.arange(0.5, 0.7, 0.025)"
_lambda: 0.25
gamma: 0


# task control
task_info: 'HR-Pro'
gpu: '3'



