# dataset info
# backbone: 'i3d'
backbone: 'video_swin'
dataset: "GTEA"
data_path: "./dataset/GTEA"
frames_per_sec: 15
segment_frames_num: 16
feature_dim: 2560
#feature_dim: 1024
tIoU_thresh: "np.linspace(0.1, 0.7, 7)"
blocked_videos: ['video_test_0000270','video_test_0001292','video_test_0001496'] # We excluded three test videos (270, 1292, 1496) following LACP.

# training params
num_segments: -1
num_workers: 4
num_iters: 500
test_iter: 10
batch_size: 16
lr: 0.0001
weight_decay: 0.0005
dropout: 0.7
r_act: 8
lambdas: "[0, 0.5, 1, 1]"
RAB_args: {'layer_num': 1, 'drop_out': 0.3, 'num_heads': 8, 'dim_feedforward': 128}

# stage2 params
max_epochs: 20
test_epoch: 1
batch_size2: 5
lr2: 0.00002
weight_loss_score: 1.0
weight_loss_reg: 1.0
max_proposal: 800


# post processing params
scale: 2
class_thresh: 0.2
act_thresh_cas: "np.arange(0.0, 0.25, 0.025)"
act_thresh_agnostic: "np.arange(0.5, 0.725, 0.025)"
_lambda: 0.25
gamma: 0


# task control
task_info: 'HR-Pro'
gpu: '0'



